[build]
builder = "nixpacks"

[deploy]
startCommand = "npm install && node server.js"
healthcheckPath = "/api/beats"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "beattracker"
